[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
program = { path = "../program", features = ["no-entrypoint"] }
solana-client = "1.11.7"
solana-sdk = "1.11.7"
tokio = "1.14.1"
